name: Publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches: ["master"]

jobs:
  build:
    # Ensure test job passes before pushing image.

    name: Publish binaries
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Get current date
        id: date
        run: | 
          echo "::set-output name=date::$(date +'%Y%m%d-%H%M%S')"

      - name: Build Debian Package
        id: build_package
        run: |
          ls
          pwd
          mv opt src/
          mv build-debian src/DEBIAN
          cd src
          ls
          pwd
          touch DEBIAN/md5sums
          touch DEBIAN/control
          find ./ -type f -exec md5sum {} \; > DEBIAN/md5sums
          size=$(du -s ../src | cut -f 1)
          packname="windowsrdp"
          osversion="ondokuz"
          urgency="high"
          commitmessage="$packname (${{steps.date.outputs.date}}) $osversion; urgency=$urgency
      
          - ${{github.event.head_commit.message}}
          
          -- ${{github.actor}} <${{secrets.MAIL_FROM}}>  <${{secrets.MAIL_HOST}}> $(date)
          "
          echo $commitmessage | gzip >> usr/share/doc/$packname/changelog.gz
          echo "${{toJson(github.event.commits)}}"
          echo "Package: $packname
          Version: ${{steps.date.outputs.date}}
          Installed-Size: $size
          Maintainer: Duygu Ölmez <zeynepduyguolmez@gmail.com>
          Priority: optional
          Depends: freerdp2-x11
          Date : $GITHUB_RUN_ID
          Architecture: amd64
          Description: Remote Desktop for Office
           Rdp to Remote Windows Client for Office
          " > DEBIAN/control
          cat DEBIAN/control
          chmod 755 DEBIAN/postinst
          cd ../
          sed -i "s/version: xxx/version: "$date"/g" src/usr/local/bin/smb-*
          mv src $packname-${{steps.date.outputs.date}}
          dpkg-deb -Zgzip --build $packname-${{steps.date.outputs.date}}
          mkdir dist
          pwd
          ls
          echo ::set-output name=path::$(pwd)/$packname-${{steps.date.outputs.date}}.deb
          echo ::set-output name=filename::$packname-${{steps.date.outputs.date}}.deb

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.date.outputs.date}}
          release_name: ${{steps.date.outputs.date}}
          body: |
            Changes in this Release
            - Print files in current directory
          draft: false
          prerelease: false

      - name: Upload the Debian package to Release Assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build_package.outputs.path }}
          asset_name: ${{ steps.build_package.outputs.filename }}
          asset_content_type: application/vnd.debian.binary-package
